# Generated by Django 2.0.7 on 2018-07-14 07:34

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('snippets', '0002_snippet_uuid'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='snippet',
            name='uuid',
        ),
    ]
